import momento from './momento';
import state from './state';
import iterator from './iterator';
import strategy from './strategy';
import template from './template';
// momento();
// state();
// iterator();
// strategy();
template();
